### ISSUE TITLE
app.startApp() is not a function.

### ISSUE THREAD

**Issue by Sovak3441** [AnEmortalKid/sc-refinery-tracker#11]
Thought i'd check out the this tracker, but after starting it up, all it says is a big fat error stating; app.startApp() is not a function.

**Comment by AnEmortalKid** [comment]
Odd... I usually build it with:

npm run build

that should create an app module that gets dropped on the global space.

**Comment by Sovak3441** [comment]
Ahh, okay! I just ran a start:dev to check it out :)
After a build it worked :)

**Comment by AnEmortalKid** [comment]
Ah, @Sovak3441 was the steps just 

npm run build
npm start:dev 

If so , I can update that somewhere in the readme. I never got the start dev to work and was always referencing things from dist... but if that works then that’s fantastic and is gonna save me a lot of time.
