### ISSUE TITLE
Request sorting function on columns

### ISSUE THREAD

**Issue by TaunHawk** [AnEmortalKid/sc-refinery-tracker#29]
Requesting either a sort option for each column or maybe adding folders. See attached screenshot:
![Sort Option](https://user-images.githubusercontent.com/113890210/190980037-b8a69190-9466-4263-9db1-6354b5a5b16d.png)

**Comment by AnEmortalKid** [comment]
Hmm, well multi-sort and folders are going to be tricky, but I can quickly implement single column sorting if that would do what you want at the moment!

**Comment by TaunHawk** [comment]
Yes, sorry I had hoped that request wasn't confusing. I mean either sorting or folders, both options are not needed. Also, I mean the ability to sort either of those columns, but not multiple columns at the same time. So yea that would be fantastic if I could just sort one of the columns such as from top to bottom all that are done, or all that have similar durations or all from same location, etc.

**Comment by AnEmortalKid** [comment]
Ok yeah, single sort is much easier. I’ll started on that this morning and will get it to you ASAP !

**Comment by TaunHawk** [comment]
Thank you! :) :) :)

**Comment by AnEmortalKid** [comment]
@TaunHawk this is live now

![image](https://user-images.githubusercontent.com/3474369/191136352-22da739e-b615-4d3b-98a1-77583ffacd56.png)


LMK if you ran into other issues

**Comment by TaunHawk** [comment]
Just tested it, it works perfect! Thank you for this wonderful community tool
